---
title: "dictionary based"
author: "Sanja"
date: "30 July 2018"
output: html_document
---
```{r}
require("quanteda")
require("magrittr")

cast_to_corpus <- function(corp) {
  # In: corp, a dataset with a 'text' attribute
  # Out: a corpus object
  return (corpus(corp$text))
}

cast_to_dfm <- function (corp, stops) {
  # In: corp: a corpus object
  #     stops: any additional stop words to include
  # Out: a dfm object
  
  return (dfm(corp, stem=T, remove_numbers = TRUE, remove_punct = TRUE, remove_symbols = TRUE,  remove = stops))
}

dictionary_lookup_to_df <- function (corpus_dfm, dict) {
  return(convert(dfm_lookup(corpus_dfm, dictionary = dict), to = "data.frame"))
}

add_sum_column <- function(result_df){
  result_df$value_sum = rowSums(result_df[,-1])
  return(result_df)
}
```

```{r}
# dictionary

mig_dict_full <- dictionary (list (toleran= c("*toleran*"), abuse = c("abuse"), assimil =	c("assimil*"), asylum =	c(	"asylum*"	), avalanche =	c("avalanche"), border	=	c("border"), burqa=	c("burqa"), christian=	c("christian"), citizen=	c("citizen*"), cultur =	c("cultur*"), custom	=	c("custom*"), deport	=	c("deport*"), discriminat=	c("discriminat*"), diversity =	c("diversity"), ethnic	=	c("ethnic*"), extremis	=	c("extremis*"), flood =	c(	"flood"	), foreign=	c("foreign*"),fraud	=	c("fraud"	)	, halal	=	c("halal"	), hallal	=	c("hallal"), headscarf=	c("headscarf"), human=	c	(	"human*"), identitiy= c("identitiy"), illegal=	c("illegal*"), immigr	=	c	("immigr*"), indigenous=	c	("indigenous"),	integrat=	c("integrat*"	), invasion=		c("invasion"	),	irregular=	c(	"irregular"),	islam	=	c("islam*"),	jihad	=	c("jihad*"), migrant=	c("migrant*"),	minaret	=	c	(	"minaret"	), minorit=		c("minorit*"),	mosque	=	c ("mosque"), multicultur =	c("multicultur*"), muslim	= c("muslim"), nation		= c("nation*"),	native	= c("native"), naturalis=	c("naturalis*"), naturaliz=	c("naturaliz*"), permit	= c("permit"),	raci =	c("raci*"),	radical	=	c("radical"),	refug	=	c("refug*"),	refuge	=	c(	"refuge"),	religious =	c("religious"),	reunion	=	c	("reunion"), sharia	=	c ("sharia"	), shari	=	c("shari'a"),	shariah	=	c("shariah"), shelter	=	c("shelter"), temple	=	c(	"temple")	,	terroris =	c("terroris*"), tradition = c("tradition*"), traumatis =	c("traumatis"),	traumatiz =	c("traumatiz*"), unauthorised = c("unauthorised"), unauthorized =	c("unauthorized"), unity	= c("unity"),	veil = c("veil"), xenophob =	c("xenophob*")))

```



```{r}

# "Dictionary approach"
load("Corp_HouseOfCommons.RData")

dict_dfm <- hoc.corpus %>% cast_to_corpus() %>% cast_to_dfm(stops = stopwords("en"))  %>% dictionary_lookup_to_df(dict = mig_dict_full) 
 
trim_df = hoc.corpus[rowSums(dict_dfm[,-1]) > 0,] # take only those which sum to at least 1

# at this point we have a reduced form of the hoc.corpus for which only records with migration related words are included

# Now we move on to extracting the value-laden words and counting them up

# valuesdictionary.txt is a file which contains value regex expressions
values_dict = dictionary(file = "Values_LIWC_Jul_31.txt", format = "LIWC", sep = ",")

# take our reduced matrix and run the same pipeline as above, but with values
# in the dictionary
values_results <- trim_df %>% cast_to_corpus() %>% cast_to_dfm(stops = stopwords("en"))  %>% dictionary_lookup_to_df(dict = values_dict) %>% add_sum_column()

# bind the original, trimmed dataframe, and the value results
values_joined = cbind(values_results, trim_df)

# save it all to a csv
write.csv(values_joined, file = "joined_value_counts.csv")


```



```{r}

rm(values_results)
rm(values_joined)
rm(dict_dfm)
rm(trim_df)
# "Topic Model Approach"

hoc.corpus = read.csv("hoc_subset_corpus_2005-2015.csv", stringsAsFactors = FALSE)

# at this point we have a reduced form of the hoc.corpus for which only records with migration related words are included, from a topic model

# Now we move on to extracting the value-laden words and counting them up

# valuesdictionary.txt is a file which contains value regex expressions
values_dict = dictionary(file = "Values_LIWC_Jul_31.txt", format = "LIWC", sep = ",")

# take our reduced matrix and run the same pipeline as above, but with values
# in the dictionary
values_results <- hoc.corpus %>% cast_to_corpus() %>% cast_to_dfm(stops = stopwords("en"))  %>% dictionary_lookup_to_df(dict = values_dict) %>% add_sum_column()

# bind the original, trimmed dataframe, and the value results
values_joined = cbind(values_results, hoc.corpus)

# save it all to a csv
write.csv(values_joined, file = "joined_value_counts_from_topic_model.csv")
rm(hoc.corpus)
rm(values_joined)
rm(values_results)
```

